name: CI with Energy Estimation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Start Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: start-measurement

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Measurement - After Checkout
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'after-checkout'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Measurement - After Setup
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'after-setup'

      - name: Run tests
        run: pytest

      - name: Measurement - After Tests
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'after-tests'

      - name: Show Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: display-results
